### ISSUE TITLE
Error importing Pyriod

### ISSUE THREAD

**Issue by gferrini** [keatonb/Pyriod#10]
Hi,

using Jupyter Notebooks, I have thi issue importing Pyriod:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_19952/133210092.py in <module>
      1 get_ipython().run_line_magic('matplotlib', 'widget')
----> 2 from Pyriod import Pyriod

~/anaconda3/lib/python3.9/site-packages/Pyriod/__init__.py in <module>
      1 from __future__ import absolute_import
      2 
----> 3 from .Pyriod import Pyriod

~/anaconda3/lib/python3.9/site-packages/Pyriod/Pyriod.py in <module>
     41 from lmfit import Model, Parameters
     42 from bs4 import BeautifulSoup
---> 43 from bs4.builder import XMLParsedAsHTMLWarning
     44 import matplotlib.pyplot as plt
     45 from matplotlib.widgets import LassoSelector

ImportError: cannot import name 'XMLParsedAsHTMLWarning' from 'bs4.builder' (/home/gianfranco/anaconda3/lib/python3.9/site-packages/bs4/builder/__init__.py)

**Comment by keatonb** [comment]
Thanks for reporting this issue! It's a new one.  Can you please check what version of beautifulsoup4 you have installed?

**Comment by gferrini** [comment]
I have tried  with a Linux and a Windwos systems: in both I have the version 4.0.10 of beautifulsoup4.

**Comment by keatonb** [comment]
Can you please try to reinstall beautifulsoup4 with `pip install --upgrade --force-reinstall beautifulsoup4`?

Another colleague of mine ran into this issue recently and this solved the problem for her.

**Comment by gferrini** [comment]
I also solved it with pip install --upgrade --force-reinstall beautifulsoup4.
Thanks
