### ISSUE TITLE
Errors with interactive parts of Pyriod

### ISSUE THREAD

**Issue by DerekAstro** [keatonb/Pyriod#12]
Keaton,

I'm having an issue with Pyriod which I'm sure is due to something stupid on my part, since my Python-fu is pretty limited. I have no problem running Pyriod() on some light curve file, but when I try to run anything interactive, like Pyriod.TimeSeries(), I get the error below. I recognize that this is likely an issue with my limited understanding of Python and/or Conda, but I'm still hoping you can provide some guidance? I have run %matplotlib widget in an earlier cell. Thanks!

Derek

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [30], line 1
----> 1 Pyriod.TimeSeries(ar_cas_lc)

File ~/anaconda3/envs/lk/lib/python3.9/site-packages/Pyriod/Pyriod.py:1801, in Pyriod.TimeSeries(self)
   1793 def TimeSeries(self):
   1794     """Display the interactive Time Series cell in a Jupyter notebook.
   1795 
   1796     Returns
   (...)
   1799         Time series plot, options, and information to be displayed.
   1800     """
-> 1801     if self.gui:
   1802         options = widgets.Accordion(children=[
   1803             VBox([self._tstype, self._fold, self._fold_on,
   1804                   self._select_fold_freq, self._reset_mask])], selected_index=None)
   1805         options.set_title(0, 'options')

File ~/anaconda3/envs/lk/lib/python3.9/site-packages/lightkurve/lightcurve.py:355, in LightCurve.__getattr__(self, name, **kwargs)
    353     elif name.upper() in self.__dict__["_meta"]:
    354         return self.__dict__["_meta"][name.upper()]
--> 355 raise AttributeError(f"object has no attribute {name}")

AttributeError: object has no attribute gui

**Comment by keatonb** [comment]
Hey Derek!  You want to make the Pyriod instance like
`pyriod = Pyriod(ar_cas_lc)` and then run `pyriod.TimeSeries()` a method of that instance with no arguments.  Let me know if you run into any other issues.

**Comment by keatonb** [comment]
See the example notebook here: https://github.com/keatonb/Pyriod/blob/master/examples/TESS_DBV_example.ipynb
