### ISSUE TITLE
Issue Viewing the Table of Periods

### ISSUE THREAD

**Issue by Ndresier** [keatonb/Pyriod#13]
Hello Keaton,

I'm having a strange issue with Pyriod that my advisor and I can't figure out. When I use .TimeSeries() and .Periodogram(), there's nothing wrong with the graphs, and I'm able to interact with them and collect a list of periods. However, when I try to view the table of periods under .Signals() or .Pyriod(), nothing shows on-screen, so I have no access to the list of periods I've created. It appears to be running the code just fine because I do not get an error message, either (I attached an image so you can see what I mean). Since everything else works, I think the table is what's causing those problems. I'm wondering if you know anything about this issue and if there's a fix. My advisor thinks it could be Windows-related, but I'm not sure how that would work or why it would be the case. Please let me know if you need any more details.

Thank you in advance,
Nathan Dreiser

<img width="812" alt="PyriodSignalsIssue" src="https://user-images.githubusercontent.com/102268586/216171784-99457941-f0e9-49e5-b21f-8da69125f911.png">

**Comment by keatonb** [comment]
Hi Nathan,

Have you enabled the Jupyter notebook extensions?
```
jupyter nbextension enable --py --sys-prefix qgrid
jupyter nbextension enable --py --sys-prefix widgetsnbextension
jupyter nbextension enable --py --sys-prefix ipympl
```

If not, try that and then entirely restart your notebook *server*.

I haven't tested this code on Windows, but I think it should work.

Keaton

**Comment by Ndresier** [comment]
I think when I installed Pyriod I had forgotten to enable widgetsnbextension. I re-enabled all of them just in case and now  .Signals() and .Pyriod() seem to be working just fine. Thank you!

Nathan Dreiser

**Comment by keatonb** [comment]
Glad to hear it! Don't hesitate to let me know if you encounter any other
issues.

Keaton
