### ISSUE TITLE
difference in periodogram between Pyriod and Lightkurve 

### ISSUE THREAD

**Issue by harryyeh2007** [keatonb/Pyriod#15]
Hi! 

Incredible package! I am very much enjoying the interactive tool so far, just one thing, is there any possibility to change the unit on the x-axis of the periodogram to 1/day as frequency instead of muHz?

Harry

**Comment by keatonb** [comment]
When you instantiate the Pyriod object you can pass the `freq_unit = 'perday'` option for 1/day frequency units.
