### ISSUE TITLE
Pyriod and AAVSO database

### ISSUE THREAD

**Issue by pythonPleiades** [keatonb/Pyriod#18]
Excellent package and tutorials. Instead of using lightkurve package to import dataset (which is a must in the tutorial), is there a way to open CSV file so we can use Pyriod with AAVSO database?
Cheers

**Comment by keatonb** [comment]
Hi, yes you can! You can read in the CSV data in Python, either manually parsing the file or using function from [numpy](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html) or [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). Make separate arrays for the time column (in units of days), flux, and flux_err (optional). Then construct a [lightkurve.LightCurve](https://docs.lightkurve.org/reference/api/lightkurve.LightCurve.html) object to pass to Pyriod:

```Python
lc = lk.LightCurve(time = time, flux = flux, flux_err = flux_err)
pyriod = Pyriod(lc)
```
