### ISSUE TITLE
Encountering "Unmasked Data" Error with Light Curve Data

### ISSUE THREAD

**Issue by AathilAbdullah** [keatonb/Pyriod#20]
Hello,

I am encountering an "unmasked data" error while using the pyriod package for analyzing my light curve data.

Error Message:
TypeError:"unmasked data"

Request:

Could you please provide guidance on how to handle or resolve this "unmasked data" error? If there are specific data formatting requirements or additional steps I should take, I would greatly appreciate your advice.

Thank you for your assistance!

Best regards,
Aathil.

**Comment by keatonb** [comment]
I believe this is fixed in Pyriod v0.3.0. Please reopen an issue if you're still encountering this error, thanks!
