### ISSUE TITLE
Issue arising from pandas 1.0.1 update 

### ISSUE THREAD

**Issue by ConnorJarvis16** [keatonb/Pyriod#3]
Upon running the example code:

%matplotlib widget
import lightkurve as lk
from Pyriod import Pyriod
lc = lk.search_lightcurvefile('TIC 257459955',mission='TESS',sector=3).download().get_lightcurve("PDCSAP_FLUX").flatten(2161).remove_outliers(5)
pyriod = Pyriod.(lc)

the following error occurs "AttributeError: module 'pandas.core' has no attribute 'index'".

This is likely to have arisen from the update to pandas 1.0.1 version where "pandas.core.index has been deprecated and will be removed in a future version, the public classes are available in the top-level namespace (GH19711)" (see https://pandas.pydata.org/docs/whatsnew/v1.0.0.html).

**Comment by keatonb** [comment]
Yes, qgrid broke with the pandas 1.0 release (https://github.com/quantopian/qgrid/issues/287). This is fixed on the github version of qgrid (https://github.com/quantopian/qgrid/pull/290), but not on PyPI yet.  You can install the github version yourself, but you'll need [Node.js and npm](https://www.npmjs.com/get-npm) for that.  Or you can wait for that update to become pip installable and use pandas < 1.0 in the meantime.

Thanks for the report!

**Comment by jongablop** [comment]
Does anyone know when will be released the fixed version?

**Comment by keatonb** [comment]
@footballguy16 This bug should have been fixed in the newest version 1.3.0 of qgrid.
