### ISSUE TITLE
TESS_DBV_example.ipynb AttributeError: object has no attribute get_lightcurve

### ISSUE THREAD

**Issue by JosephKarpinski** [keatonb/Pyriod#4]
https://github.com/keatonb/Pyriod/blob/master/examples/TESS_DBV_example.ipynb

import lightkurve as lk
from Pyriod import Pyriod

lc = lk.search_lightcurvefile(
'TIC 257459955',mission='TESS',sector=3).download().get_lightcurve("PDCSAP_FLUX").flatten(2161).remove_outliers(5)

AttributeError                            Traceback (most recent call last)
<ipython-input-2-a7a813fa1525> in <module>
      1 #Download light curve of a DBV white dwarf pulsator observed by TESS
----> 2 lc = lk.search_lightcurvefile('TIC 257459955',mission='TESS',sector=3).download().get_lightcurve("PDCSAP_FLUX").flatten(2161).remove_outliers(5)

~/opt/anaconda3/lib/python3.8/site-packages/lightkurve/lightcurve.py in __getattr__(self, name, **kwargs)
    335             elif name.upper() in self.__dict__["_meta"]:
    336                 return self.__dict__["_meta"][name.upper()]
--> 337         raise AttributeError(f"object has no attribute {name}")
    338 
    339     def __setattr__(self, name, value, **kwargs):

AttributeError: object has no attribute get_lightcurve

from importlib.metadata import version
print(version('lightkurve'))
2.0.9

**Comment by keatonb** [comment]
Thanks @JosephKarpinski !

The example notebook has been updated to use the formatting of the new LightKurve version 2.0 and works with the most recent version of Pyriod (0.0.13).
