### ISSUE TITLE
nsamples type issue

### ISSUE THREAD

**Issue by jjhermes** [keatonb/Pyriod#5]
I'm not sure if it's a newer numpy issue (I'm using 1.18.1) but nsamples was not being passed as an integer when defined, so Pyriod was always throwing:

TypeError: 'numpy.float64' object cannot be interpreted as an integer

I solved this by simply changing to: nsamples = int(round(osample*tspan/dt))

**Comment by keatonb** [comment]
Thanks for the report JJ.  Looks like it's actually an older numpy issue, fixed in 1.19+.  https://github.com/numpy/numpy/issues/11810

I'll modify as suggested for the next release (coming soon), but you should be able to get around this by updating numpy.
