### ISSUE TITLE
Saving the model lightcurve created by prewhitening process

### ISSUE THREAD

**Issue by tilakpawar** [keatonb/Pyriod#6]
Hello,

1. Is there a way to save the model lightcurve which is created by refining the fit in the **pyriod.Periodogram()** process? Maybe I just could not find it somehow?

2. **pyriod.Pyriod()** throws 'Error displaying widget: model not found' error. Any way around this?

Thanks in advance! :)

**Comment by keatonb** [comment]
Apologies for not seeing this sooner!

1. Yes, the model sampled as the data is stored in pyriod.lc, which has a column "model".
2. I have not encountered this error.  If you're still having trouble please copy the complete error.

Sorry again for the delay.

**Comment by tilakpawar** [comment]
Hello,
No worries, I did switch to a different method meanwhile but I am glad that you replied. Thank you!
I got pyriod working again for my case study. jupyter lab was the problem which I ignored last time. Everything works fine now in jupyter notebook. Also found the model in 'pyriod.lc' like you said. I guess this will definitely help me in my work in the near future! :)
Cheers!
