### ISSUE TITLE
False Alarm Probability calculation within the code

### ISSUE THREAD

**Issue by tilakpawar** [keatonb/Pyriod#8]
Hi Keaton, 

Is there any development on the False Alarm Probability calculation within the code?

**Comment by keatonb** [comment]
No, but this is something I plan to work at some point in the next month.  I will comment here when I have implemented something.  Do you have a preferred approach to calculating the FAP?

**Comment by tilakpawar** [comment]
My work mostly demands frequency analysis for asteroseismology. Usually, I stick to the Signal-to-Noise of frequency amplitude >=4 criteria (Breger et al. (1993)) but this is partly because I haven't explored other (more complicated or robust) methods yet.
I will be looking forward to the update. Thanks in advance!

**Comment by keatonb** [comment]
Pyriod v0.2.1 now has the ability to calculate a significance threshold similar to how Period04 did. In the GUI, the widgets for computing a significance threshold are located under the Periodogram options dropdown.  The significance threshold is take as the average amplitude in the residuals periodogram computed in a sliding window, times a scaling factor (Breger et al., 1993 suggests 4, but a higher value should be used for extensive space-based data).
